package:
  name: twofish
  version: "0.3.0"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - twofish
